# =============================================================================
# Mobile Build - Festival React Native / Expo App
# =============================================================================
# Builds Android APK and iOS app for the mobile application
# Uses EAS Build for production builds, local builds for development
# =============================================================================

name: Mobile Build

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/mobile/**'
      - 'libs/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/mobile.yml'
  pull_request:
    branches: [main]
    paths:
      - 'apps/mobile/**'
      - 'libs/**'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - android
          - ios
      build_type:
        description: 'Build type'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - preview
          - production

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  # ===========================================================================
  # Lint & Test Mobile App
  # ===========================================================================
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache NX
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: nx-mobile-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            nx-mobile-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-
            nx-mobile-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Lint mobile application
        run: npx nx lint mobile
        continue-on-error: true

      - name: Run type check
        run: npx nx run mobile:typecheck
        continue-on-error: true

      - name: Run unit tests
        run: npx nx test mobile --coverage
        continue-on-error: true

      - name: Upload test coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/apps/mobile/lcov.info
          flags: mobile
          name: codecov-mobile
        continue-on-error: true

  # ===========================================================================
  # Build Android APK (Ubuntu runner)
  # ===========================================================================
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: test
    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' && (github.event.inputs.platform == 'all' || github.event.inputs.platform == 'android')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('apps/mobile/android/**/*.gradle*', 'apps/mobile/android/**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Install Expo CLI
        run: npm install -g expo-cli eas-cli

      - name: Setup Expo
        run: |
          cd apps/mobile
          npx expo login --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        continue-on-error: true

      # Option 1: EAS Build (Recommended for production)
      - name: Build with EAS (Production)
        if: github.event.inputs.build_type == 'production'
        run: |
          cd apps/mobile
          eas build --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Option 2: Local build for development/preview
      - name: Build Android APK (Development)
        if: github.event.inputs.build_type != 'production'
        run: |
          cd apps/mobile
          # Generate native project if using Expo managed workflow
          npx expo prebuild --platform android --clean
          # Build APK
          cd android
          ./gradlew assembleRelease
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        continue-on-error: true

      - name: Sign APK
        if: github.event.inputs.build_type != 'production'
        run: |
          echo "Signing APK..."
          # TODO: Add APK signing commands if not using EAS
        continue-on-error: true

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-${{ github.sha }}
          path: |
            apps/mobile/android/app/build/outputs/apk/release/*.apk
          retention-days: 30
        continue-on-error: true

      - name: Upload to Play Store (Internal Testing)
        if: github.ref == 'refs/heads/main' && github.event.inputs.build_type == 'production'
        run: |
          echo "Uploading to Play Store Internal Testing track..."
          # TODO: Add fastlane or Play Store API integration
          # fastlane android internal
        continue-on-error: true

  # ===========================================================================
  # Build iOS (macOS runner required)
  # ===========================================================================
  build-ios:
    name: Build iOS
    runs-on: macos-14
    needs: test
    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' && (github.event.inputs.platform == 'all' || github.event.inputs.platform == 'ios')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: |
            apps/mobile/ios/Pods
            ~/Library/Caches/CocoaPods
          key: pods-${{ runner.os }}-${{ hashFiles('apps/mobile/ios/Podfile.lock') }}
          restore-keys: |
            pods-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Install Expo CLI
        run: npm install -g expo-cli eas-cli

      - name: Setup Expo
        run: |
          cd apps/mobile
          npx expo login --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        continue-on-error: true

      # Option 1: EAS Build (Recommended for production)
      - name: Build with EAS (Production)
        if: github.event.inputs.build_type == 'production'
        run: |
          cd apps/mobile
          eas build --platform ios --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Option 2: Local build for development/preview
      - name: Install CocoaPods dependencies
        if: github.event.inputs.build_type != 'production'
        run: |
          cd apps/mobile
          npx expo prebuild --platform ios --clean
          cd ios
          pod install
        continue-on-error: true

      - name: Setup iOS signing
        if: github.event.inputs.build_type != 'production'
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.IOS_P12_BASE64 }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}
        continue-on-error: true

      - name: Install provisioning profile
        if: github.event.inputs.build_type != 'production'
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
        continue-on-error: true

      - name: Build iOS app
        if: github.event.inputs.build_type != 'production'
        run: |
          cd apps/mobile/ios
          xcodebuild -workspace Festival.xcworkspace \
            -scheme Festival \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/Festival.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="${{ secrets.IOS_CODE_SIGN_IDENTITY }}" \
            PROVISIONING_PROFILE_SPECIFIER="${{ secrets.IOS_PROVISIONING_PROFILE_NAME }}" \
            DEVELOPMENT_TEAM="${{ secrets.IOS_TEAM_ID }}"
        continue-on-error: true

      - name: Export IPA
        if: github.event.inputs.build_type != 'production'
        run: |
          cd apps/mobile/ios
          xcodebuild -exportArchive \
            -archivePath $PWD/build/Festival.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist ExportOptions.plist
        continue-on-error: true

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa-${{ github.sha }}
          path: |
            apps/mobile/ios/build/*.ipa
          retention-days: 30
        continue-on-error: true

      - name: Upload to TestFlight
        if: github.ref == 'refs/heads/main' && github.event.inputs.build_type == 'production'
        run: |
          echo "Uploading to TestFlight..."
          # TODO: Add fastlane or App Store Connect API integration
          # fastlane ios beta
        continue-on-error: true

  # ===========================================================================
  # Notify Build Status
  # ===========================================================================
  notify:
    name: Notify Build Status
    runs-on: ubuntu-latest
    needs: [build-android, build-ios]
    if: always()
    steps:
      - name: Check build status
        run: |
          echo "Android build: ${{ needs.build-android.result }}"
          echo "iOS build: ${{ needs.build-ios.result }}"

      - name: Notify on success
        if: needs.build-android.result == 'success' || needs.build-ios.result == 'success'
        run: |
          echo "Mobile build completed successfully!"
          # TODO: Add Slack/Discord notification
          # curl -X POST -H 'Content-type: application/json' \
          #   --data '{"text":"Mobile build completed: Android=${{ needs.build-android.result }}, iOS=${{ needs.build-ios.result }}"}' \
          #   ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify on failure
        if: needs.build-android.result == 'failure' && needs.build-ios.result == 'failure'
        run: |
          echo "Mobile build failed!"
          exit 1
