# ============================================================================
# Patroni Configuration
# Festival Management Platform - High Availability PostgreSQL Cluster
# ============================================================================
# Patroni provides automatic failover and cluster management for PostgreSQL
# Documentation: https://patroni.readthedocs.io/
# ============================================================================

scope: festival-cluster
namespace: /festival/
name: patroni-node-1

# -----------------------------------------------------------------------------
# REST API Configuration
# -----------------------------------------------------------------------------
restapi:
  listen: 0.0.0.0:8008
  connect_address: ${PATRONI_HOST}:8008
  certfile: /etc/patroni/ssl/patroni.crt
  keyfile: /etc/patroni/ssl/patroni.key
  cafile: /etc/patroni/ssl/ca.crt
  verify_client: optional
  authentication:
    username: patroni_admin
    password: ${PATRONI_ADMIN_PASSWORD}

# -----------------------------------------------------------------------------
# Distributed Configuration Store (DCS)
# Using etcd for leader election and configuration storage
# -----------------------------------------------------------------------------
etcd3:
  hosts:
    - etcd-1.festival.local:2379
    - etcd-2.festival.local:2379
    - etcd-3.festival.local:2379
  protocol: https
  cacert: /etc/etcd/ssl/ca.crt
  cert: /etc/etcd/ssl/client.crt
  key: /etc/etcd/ssl/client.key
  username: patroni
  password: ${ETCD_PASSWORD}

# Alternative: Consul
# consul:
#   host: consul.festival.local:8500
#   scheme: https
#   token: ${CONSUL_TOKEN}
#   verify: true
#   cacert: /etc/consul/ssl/ca.crt
#   cert: /etc/consul/ssl/client.crt
#   key: /etc/consul/ssl/client.key
#   dc: dc1
#   consistency: default
#   register_service: true

# Alternative: ZooKeeper
# zookeeper:
#   hosts:
#     - zk-1.festival.local:2181
#     - zk-2.festival.local:2181
#     - zk-3.festival.local:2181

# Alternative: Kubernetes
# kubernetes:
#   namespace: festival
#   labels:
#     application: patroni
#     cluster-name: festival-cluster
#   use_endpoints: true
#   pod_ip: ${POD_IP}
#   ports:
#     - name: postgresql
#       port: 5432

# -----------------------------------------------------------------------------
# Bootstrap Configuration (Initial Cluster Setup)
# -----------------------------------------------------------------------------
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576  # 1MB max lag for failover
    maximum_lag_on_syncnode: -1       # No limit for sync standby
    primary_start_timeout: 300
    primary_stop_timeout: 30
    synchronous_mode: true            # Enable synchronous replication
    synchronous_mode_strict: false    # Allow async if no sync standby
    synchronous_node_count: 1         # Number of sync standbys

    postgresql:
      use_pg_rewind: true
      use_slots: true

      parameters:
        # Replication
        wal_level: replica
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_size: 2GB
        hot_standby: 'on'
        hot_standby_feedback: 'on'

        # Memory
        shared_buffers: 8GB
        effective_cache_size: 24GB
        work_mem: 64MB
        maintenance_work_mem: 2GB

        # WAL
        wal_buffers: 256MB
        checkpoint_timeout: 15min
        max_wal_size: 4GB
        min_wal_size: 1GB
        checkpoint_completion_target: 0.9

        # Archiving
        archive_mode: 'on'
        archive_command: '/usr/local/bin/wal-archive.sh %p %f'
        archive_timeout: 300

        # Autovacuum
        autovacuum: 'on'
        autovacuum_max_workers: 4
        autovacuum_vacuum_scale_factor: 0.05
        autovacuum_analyze_scale_factor: 0.02

        # Logging
        log_destination: 'stderr'
        logging_collector: 'on'
        log_min_duration_statement: 500
        log_checkpoints: 'on'
        log_lock_waits: 'on'

        # Security
        ssl: 'on'
        ssl_cert_file: '/etc/postgresql/ssl/server.crt'
        ssl_key_file: '/etc/postgresql/ssl/server.key'
        ssl_ca_file: '/etc/postgresql/ssl/ca.crt'
        password_encryption: 'scram-sha-256'

        # Performance
        shared_preload_libraries: 'pg_stat_statements'
        pg_stat_statements.max: 10000
        pg_stat_statements.track: 'all'

        # Timeouts
        statement_timeout: 60000
        lock_timeout: 30000
        idle_in_transaction_session_timeout: 300000

  # Initial database and users
  initdb:
    - encoding: UTF8
    - data-checksums
    - locale: en_US.UTF-8

  # Post-init SQL scripts
  post_init: /etc/patroni/post_init.sh

  # Users to create
  users:
    admin:
      password: ${POSTGRES_ADMIN_PASSWORD}
      options:
        - createrole
        - createdb

    festival_app:
      password: ${FESTIVAL_APP_PASSWORD}
      options: []

    festival_readonly:
      password: ${FESTIVAL_READONLY_PASSWORD}
      options: []

    replicator:
      password: ${REPLICATOR_PASSWORD}
      options:
        - replication

    backup:
      password: ${BACKUP_PASSWORD}
      options:
        - replication

# -----------------------------------------------------------------------------
# PostgreSQL Configuration
# -----------------------------------------------------------------------------
postgresql:
  listen: 0.0.0.0:5432
  connect_address: ${PATRONI_HOST}:5432
  data_dir: /var/lib/postgresql/data
  bin_dir: /usr/lib/postgresql/16/bin
  config_dir: /etc/postgresql/16/main

  # Authentication
  authentication:
    superuser:
      username: postgres
      password: ${POSTGRES_PASSWORD}
      sslmode: verify-full
      sslcert: /etc/postgresql/ssl/postgres.crt
      sslkey: /etc/postgresql/ssl/postgres.key
      sslrootcert: /etc/postgresql/ssl/ca.crt

    replication:
      username: replicator
      password: ${REPLICATOR_PASSWORD}
      sslmode: verify-full

    rewind:
      username: postgres
      password: ${POSTGRES_PASSWORD}
      sslmode: verify-full

  # Custom HBA configuration
  pg_hba:
    - local   all             postgres                                peer
    - local   all             all                                     scram-sha-256
    - hostssl all             all             127.0.0.1/32            scram-sha-256
    - hostssl all             all             ::1/128                 scram-sha-256
    - hostssl replication     replicator      10.0.0.0/8              scram-sha-256
    - hostssl replication     replicator      172.16.0.0/12           scram-sha-256
    - hostssl all             all             10.0.0.0/8              scram-sha-256
    - hostssl all             all             172.16.0.0/12           scram-sha-256
    - host    all             all             0.0.0.0/0               reject

  # Base backup configuration for pg_rewind
  basebackup:
    - checkpoint: fast
    - wal-method: stream

  # Recovery configuration
  recovery_conf:
    restore_command: '/usr/local/bin/wal-restore.sh %f %p'

  # Custom callbacks
  callbacks:
    on_start: /etc/patroni/callbacks/on_start.sh
    on_stop: /etc/patroni/callbacks/on_stop.sh
    on_restart: /etc/patroni/callbacks/on_restart.sh
    on_role_change: /etc/patroni/callbacks/on_role_change.sh
    on_reload: /etc/patroni/callbacks/on_reload.sh

  # Create replica methods
  create_replica_methods:
    - pgbackrest
    - basebackup

  pgbackrest:
    command: /usr/bin/pgbackrest --stanza=festival --delta restore
    keep_data: true
    no_params: true

  basebackup:
    max-rate: '100M'
    checkpoint: fast
    wal-method: stream

# -----------------------------------------------------------------------------
# Watchdog (Linux Kernel Watchdog for Split-Brain Prevention)
# -----------------------------------------------------------------------------
watchdog:
  mode: automatic  # off, automatic, or required
  device: /dev/watchdog
  safety_margin: 5

# -----------------------------------------------------------------------------
# Tags for Node Classification
# -----------------------------------------------------------------------------
tags:
  nofailover: false      # Set true to exclude from failover
  noloadbalance: false   # Set true to exclude from read load balancing
  clonefrom: false       # Set true to allow as clone source
  nosync: false          # Set true to exclude from sync replication
  replicatefrom: ''      # Specific node to replicate from (cascading)

# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------
log:
  level: INFO
  format: '%(asctime)s %(levelname)s: %(message)s'
  dateformat: '%Y-%m-%d %H:%M:%S'
  max_queue_size: 1000
  dir: /var/log/patroni
  file_num: 10
  file_size: 25000000  # 25MB

# ============================================================================
# Multi-AZ Deployment Notes
# ============================================================================
# For Multi-AZ setup, deploy nodes in different availability zones:
#
# Node 1 (Primary):     AZ-A  (eu-west-1a)
# Node 2 (Sync Replica): AZ-B  (eu-west-1b)
# Node 3 (Async Replica): AZ-C  (eu-west-1c)
#
# etcd cluster should also span multiple AZs for HA.
#
# Network latency between AZs should be < 2ms for sync replication.
# Use async replication for cross-region DR.
# ============================================================================
