#!/bin/bash
# ============================================================================
# PostgreSQL Replica Initialization Script
# Festival Management Platform
# ============================================================================
# This script sets up streaming replication from the primary server
# ============================================================================

set -e

echo "Initializing PostgreSQL Replica: ${REPLICA_NAME:-replica}..."

# Configuration
PRIMARY_HOST="${PRIMARY_HOST:-postgres-primary}"
REPLICA_NAME="${REPLICA_NAME:-replica1}"
SLOT_NAME="${REPLICA_NAME}_slot"
PGDATA="${PGDATA:-/var/lib/postgresql/data/pgdata}"

# Wait for primary to be ready
echo "Waiting for primary server at ${PRIMARY_HOST}..."
until pg_isready -h "$PRIMARY_HOST" -p 5432 -U "${POSTGRES_USER:-festival_admin}"; do
    echo "Primary is not ready yet. Waiting..."
    sleep 5
done

echo "Primary server is ready!"

# Check if this is first-time setup (data directory empty or no valid PostgreSQL data)
if [ ! -s "$PGDATA/PG_VERSION" ]; then
    echo "Performing initial base backup from primary..."

    # Clean the data directory
    rm -rf "$PGDATA"/*

    # Perform base backup
    export PGPASSWORD="${REPLICATOR_PASSWORD:-replicator_secret}"

    pg_basebackup \
        --host="$PRIMARY_HOST" \
        --port=5432 \
        --username=replicator \
        --pgdata="$PGDATA" \
        --wal-method=stream \
        --slot="$SLOT_NAME" \
        --checkpoint=fast \
        --progress \
        --verbose \
        2>&1

    # Create standby.signal to indicate this is a standby
    touch "$PGDATA/standby.signal"

    # Configure replication connection
    cat >> "$PGDATA/postgresql.auto.conf" <<EOF

# Streaming Replication Configuration
# Generated by init-replica.sh
primary_conninfo = 'host=${PRIMARY_HOST} port=5432 user=replicator password=${REPLICATOR_PASSWORD:-replicator_secret} application_name=${REPLICA_NAME} sslmode=prefer'
primary_slot_name = '${SLOT_NAME}'
recovery_target_timeline = 'latest'
hot_standby = on
hot_standby_feedback = on

# Replica-specific settings
max_standby_streaming_delay = 30s
max_standby_archive_delay = 300s
wal_receiver_status_interval = 10s
wal_receiver_timeout = 60s
EOF

    # Set proper permissions
    chmod 0700 "$PGDATA"
    chown -R postgres:postgres "$PGDATA"

    echo "Base backup complete. Replica is ready to start."
else
    echo "Data directory exists. Checking standby status..."

    # Ensure standby.signal exists
    if [ ! -f "$PGDATA/standby.signal" ]; then
        echo "Creating standby.signal..."
        touch "$PGDATA/standby.signal"
    fi
fi

echo "Replica initialization complete!"
